require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/**/*

RSpec/NestedGroups:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - spec/tasks/**/*
